// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMjmLuQ7Gm011jH_FjeIs4Jh9EZ3qes_g',
    appId: '1:291607668768:web:3c8ddd6bf8ea70c331b445',
    messagingSenderId: '291607668768',
    projectId: 'tmms-8a2ab',
    authDomain: 'tmms-8a2ab.firebaseapp.com',
    databaseURL: 'https://tmms-8a2ab-default-rtdb.firebaseio.com',
    storageBucket: 'tmms-8a2ab.appspot.com',
    measurementId: 'G-SFTLZRDS9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuU0zik2k0mtMitqXvpXq0CkbygBipvBQ',
    appId: '1:291607668768:android:eecc68ff7355fef531b445',
    messagingSenderId: '291607668768',
    projectId: 'tmms-8a2ab',
    databaseURL: 'https://tmms-8a2ab-default-rtdb.firebaseio.com',
    storageBucket: 'tmms-8a2ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjoc-5sc9VHL5u6qYRb3cVGGMwcP1dO34',
    appId: '1:291607668768:ios:f554b663167ac47f31b445',
    messagingSenderId: '291607668768',
    projectId: 'tmms-8a2ab',
    databaseURL: 'https://tmms-8a2ab-default-rtdb.firebaseio.com',
    storageBucket: 'tmms-8a2ab.appspot.com',
    iosBundleId: 'tz.ac.tz.tmms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMjmLuQ7Gm011jH_FjeIs4Jh9EZ3qes_g',
    appId: '1:291607668768:web:b654df2d2633953c31b445',
    messagingSenderId: '291607668768',
    projectId: 'tmms-8a2ab',
    authDomain: 'tmms-8a2ab.firebaseapp.com',
    databaseURL: 'https://tmms-8a2ab-default-rtdb.firebaseio.com',
    storageBucket: 'tmms-8a2ab.appspot.com',
    measurementId: 'G-VDL36E4VEX',
  );
}
